### ISSUE TITLE
May 2017 Meetup

### ISSUE THREAD

**Issue by joelmccracken** [pghfp/tracking#1]
for tracking plans for the may meetup

**Comment by joelmccracken** [comment]
@bwongchaowart hi! I hear you're interested in speaking in May?

**Comment by bwongchaowart** [comment]
@joelmccracken I volunteered to lead a Scala workshop based on https://www.scala-exercises.org. Attendees will be able to work on the problems on that site at their own pace and pick an appropriate difficulty level to start with. There are tutorials for beginners as well as more advanced functional programming topics. Code can be compiled and executed interactively on the Scala Exercises site without additional software.

**Comment by joelmccracken** [comment]
Great! We'll slot you in for may then! thank you <3

**Comment by joelmccracken** [comment]
@bwongchaowart I filled in a couple of details here: https://www.meetup.com/Pittsburgh-Functional-Programming-Meetup/events/239294643/ 

Just wanting to prepare things for when we want to announce.
