### ISSUE TITLE
July 2017 Meetup

### ISSUE THREAD

**Issue by joelmccracken** [pghfp/tracking#3]

**Comment by RubenSandwich** [comment]
@joelmccracken This is me. I'm going to giving a talk/workshop introducing Monads the control flow they allow in JS. I'm gonna focus on the Result Monad and use lots of railroad diagrams. My hope is to slowly walk them through taking a semi long JS promise chain and turn it into using the Result Monad.

**Comment by joelmccracken** [comment]
do you want to give me an advertisement blurb for the meetup group? You can
make any changes you want to it whenever.

Thanks Ruben!! looking forward to it.

**Comment by sjfloat** [comment]
https://www.meetup.com/Pittsburgh-Functional-Programming-Meetup/events/238899957/

**Comment by RubenSandwich** [comment]
@joelmccracken Give me about a week to come up with a good name and blurb.
